### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by bimawa** [ryanmaxwell/RMUniversalAlert#17]
Guys mb add auto move calls
```objc
[viewController presentViewController:controller animated:YES completion:nil];
```
 to Main thread?

**Comment by ryanmaxwell** [comment]
I'm not sure about this, it's a programmer error to be calling UI code from anything other than the main thread - so we're just masking the error within this library if we wrap all calls to be dispatched on the main thread. Should really fix it at the call source - you would have the same problem if you called Apple's libraries directly.

**Comment by bimawa** [comment]
Yes, but all Apple do is bad practics last time :) And they  made a Swift for masking, a lot of possible errors.  I'm can't think of a way where i want call UI methods not main threads. Just for thought.
