### ISSUE TITLE
Infinity loop on iOS 7

### ISSUE THREAD

**Issue by bimawa** [ryanmaxwell/RMUniversalAlert#21]
![uialertview 2bblocks m - tcproject-ios - 5b 7e 2fdeveloping 2fprojects 2fzenmall 5d 2016-07-21 21-42-04](https://cloud.githubusercontent.com/assets/1393809/17031164/33b875b2-4f8c-11e6-8cfb-6892c53fb690.png)

**Comment by ryanmaxwell** [comment]
Can you show me the code that creates and presents the alert? It looks like it may be a conflict with A2DynamicAlert which is in your project?

**Comment by bimawa** [comment]
```Objective-c
 [RMUniversalAlert showActionSheetInViewController:self withTitle:@"Action" message:nil cancelButtonTitle:@"Cancel" destructiveButtonTitle:@"Delete"
                                    otherButtonTitles:@[@"Rename"] popoverPresentationControllerBlock:nil tapBlock:tapBlock];
  }
```

i go try create clear project and test it on my iPhone 4 with ios7

**Comment by bimawa** [comment]
Yes u right. i have two dependency:

```
UIAlertView+Blocks.h
UIAlertView+BlocksKit.h
```

**Comment by bimawa** [comment]
Yea its similar trouble: zwaldowski/BlocksKit/issues/341

i'm just remove BlockKits
