### ISSUE TITLE
circular reference 

### ISSUE THREAD

**Issue by FlyBigBird** [ryanmaxwell/RMUniversalAlert#22]
alert.hasCancelButton = cancelButtonTitle != nil;
alert.hasDestructiveButton = destructiveButtonTitle != nil;
alert.hasOtherButtons = otherButtonTitles.count > 0;
 if ([UIAlertController class]) {
        alert.alertController = [UIAlertController showAlertInViewController:viewController
                                                                   withTitle:title message:message
                                                           cancelButtonTitle:cancelButtonTitle
                                                      destructiveButtonTitle:destructiveButtonTitle
                                                           otherButtonTitles:otherButtonTitles
                                                                    tapBlock:^(UIAlertController *controller, UIAlertAction *action, NSInteger buttonIndex){
                                                                        if (tapBlock) {
                                                                            tapBlock(alert, buttonIndex);
                                                                        }
                                                                    }];
}

alert->alertController->tapBlock->alert

**Comment by ryanmaxwell** [comment]
should be fixed in 0.8
