### ISSUE TITLE
crash in ipad ios8

### ISSUE THREAD

**Issue by pengwll** [ryanmaxwell/RMUniversalAlert#3]
UIAlertController need an source view in ipad.

**Comment by ryanmaxwell** [comment]
Thanks. I haven't used it on iPads yet, but I presume this is the same as https://github.com/ryanmaxwell/UIAlertController-Blocks/issues/3 ? I'll try and check it out this weekend!

**Comment by pengwll** [comment]
Thanks for the reply :)

**Comment by ryanmaxwell** [comment]
resolved in https://github.com/ryanmaxwell/RMUniversalAlert/releases/tag/0.4
