### ISSUE TITLE
CocoaPod Issue

### ISSUE THREAD

**Issue by humayunharoon** [ryanmaxwell/RMUniversalAlert#5]
Cocoapods.org points to pod 'MBAlertView', '~> 1.1' when i search for RMUniversalAlert

**Comment by ryanmaxwell** [comment]
I'm not seeing this behaviour - can you post a screenshot? Is it affecting the ability to install the pod? Thanks

**Comment by humayunharoon** [comment]
Strainge, cocoapods is now showing the correct pod name. 
Sorry for the false alarm. Btw awesome work on the library =)

**Comment by ryanmaxwell** [comment]
no worries!
