### ISSUE TITLE
Adding textfields to Alert View

### ISSUE THREAD

**Issue by ankraft** [ryanmaxwell/RMUniversalAlert#6]
Is it possible to add additional field to an Alert View? I tried but couldn't find how to apply, for example, the `[UIAlertController addTextFieldWithConfigurationHandler]` method.

**Comment by ryanmaxwell** [comment]
RMUniversalAlert is really a lowest-common-denominator API polyfill for both UIAlertView and UIAlertController. I haven't added any polyfill functionality to bridge UIAlertController's addTextFieldWithConfigurationHandler: with UIAlertView's textFieldAtIndex: method. If you're targeting iOS8 and above - consider just using https://github.com/ryanmaxwell/UIAlertController-Blocks

**Comment by ankraft** [comment]
I guess I will do that. Thanks a lot anyway for that great wrapper!

**Comment by ryanmaxwell** [comment]
no prob!
