### ISSUE TITLE
RMUniversalAlert contains strong reference to internal alerts

### ISSUE THREAD

**Issue by RBlafford** [ryanmaxwell/RMUniversalAlert#8]
Hello. I have encountered a design issue with RMUniversal alert. I am attempting to present an alert action sheet from a UIBarButton item. On iOS 7 since the underlying alert is a UIAlertView, it is possible to keep hitting the bar button item and have multiple alerts stacked over each other. My solution is to have a weak reference of the alert view in my vc and only display if it is nil. ex:

@implemention ViewController
...
@property (nonatomic, weak) id alert;
...

- (void)barButtonSelected:(id)sender {
  if (!self.alert) {
    self.alert = [UIAlertView show... ]
  }
}

This works fine for the methods in the UIAlertView+Blocks and UIAlertController+Blocks categories. However when I replace UIAlertView/UIAlertController with RMUniversalAlert this does not work as expected. When looking through the source it appears as the reason why this isn't working is due to the strong reference that RMUniversalAlert has to its underlying alert properties.

**Comment by ryanmaxwell** [comment]
Thanks for the heads up. I'll try and check this out when I can. Pull requests are welcome if you have a recommended solution
